from Crypto.Util.number import long_to_bytes, bytes_to_long
from hashlib import sha256
from random import randint
from sage.all_cmdline import *


# Domain Parameter Definition
# Curve-ID: brainpoolP256r1

# the prime specifying the base field
p = 0xA9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5377

# the coefficients of the equation defining the elliptic curve
A = 0x7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9
B = 0x26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6

# the base point's x- and y-coordinates, respectively.
x = 0x8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262
y = 0x547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997

# the prime order of the group generated by the base point `G`
q = 0xA9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7

E = EllipticCurve(GF(p), [A, B])
G = E(x, y)

# d = randint(1, q - 1)
d = 31415926535897932384626433832795028841971693993751  # smaller than q

msgs = [
    b'Consulted perpetual of pronounce me delivered',
    b'Too months nay end change relied who beauty wishes matter',
    b'Shew of john real park so rest we on',
    b'Can you recover d?!']*4

S = []
for msg in msgs:
    h = bytes_to_long(sha256(msg).digest())
    k = randint(1, q - 1)
    r = int((k * G)[0])
    s = int(pow(k, -1, q) * (h + d * r) % q)
    S.append({'h': h, 'r': r, 's': s, 'leak': k % 2**30})

with open('output.txt', 'w') as f:
    f.write(str(S))
