from sage.all_cmdline import *
import ast


"""
This script recovers an ECDSA private key
in the case of a leakage of 30 least significant nonce bits per nonce.
It achieves this by employing
the Lenstra-Lenstra-Lovász (LLL) lattice basis reduction algorithm.

Note: This script assumes the presence of a file named 'output.txt'

Author: Alexander Sviridov
Date: 24/05/2023
"""


# Read signatures from `output.txt`

with open('output.txt', 'r') as file:
    contents = file.read()

S = ast.literal_eval(contents)


# Domain Parameter Definition
# Curve-ID: brainpoolP256r1

# the prime specifying the base field
p = 0xA9FB57DBA1EEA9BC3E660A909D838D726E3BF623D52620282013481D1F6E5377

# the coefficients of the equation defining the elliptic curve
A = 0x7D5A0975FC2C3057EEF67530417AFFE7FB8055C126DC5C6CE94A4B44F330B5D9
B = 0x26DC5C6CE94A4B44F330B5D9BBD77CBF958416295CF7E1CE6BCCDC18FF8C07B6

# the base point's x- and y-coordinates, respectively.
x = 0x8BD2AEB9CB7E57CB2C4B482FFC81B7AFB9DE27E1E3BD23C23A4453BD9ACE3262
y = 0x547EF835C3DAC4FD97F8461A14611DC9C27745132DED8E545C1D54C72F046997

# the prime order of the group generated by the base point `G`
q = 0xA9FB57DBA1EEA9BC3E660A909D838D718C397AA3B561A6F7901E0E82974856A7

E = EllipticCurve(GF(p), [A, B])
G = E(x, y)


def construct_lattice_basis(S, q, l):
    """
    Constructs and returns a lattice basis based on the given parameters.

    Args:
        -   `S` (list): List of dictionaries representing signatures.
                Each dictionary should contain the following keys:
                's', 'r', 'h', 'leak'.

        -   `q` (int): Constant value used in the calculations.

        -   `l` (int): Exponent value.

    Returns:
        (matrix): The constructed lattice basis matrix.
    """

    # Set the number of available signatures
    m = len(S)

    # Start by constructing an identity matrix multiplied by `q`
    B = q * matrix.identity(m)

    # Construct the `t` row
    t = []
    for i in range(m):
        t.append(Integer(pow(2**l * S[i]['s'], -1, q) * S[i]['r']))

    # Add `t` to the basis `B` as its `m + 1`-th row
    B = B.insert_row(m, t)

    # Construct the `u` row,
    u = []
    for i in range(m):
        u.append(Integer(pow(2**l * S[i]['s'], -1, q)
                 * (S[i]['h'] - S[i]['s'] * S[i]['leak'])))

    # Add `u` to the basis `B` as its `m + 2`-th row
    B = B.insert_row(m + 1, u)

    # Augment `B` with the vector `[0, 0, ..., 1 / 2^l, 0]`,
    # and then with the vector `[0, 0, ..., 0, -q / 2^l]`

    B = B.change_ring(QQ)  # Change basis' ring to irrational

    v = vector([0] * m + [1 / 2**l] + [0])
    B = B.augment(v)

    w = vector([0] * (m + 1) + [-q / 2**l])
    B = B.augment(w)

    return B


l = 30  # the number of leaked least significant bits per nonce

# Construct the lattice basis `B`
B = construct_lattice_basis(S, q, l)

# Apply the Lenstra–Lenstra–Lovász (LLL)
# lattice basis reduction algorithm on the lattice basis `B`,
# to obtain the resulting reduced basis `R` for the lattice
R = B.LLL()

# Find the row with the sentinel element `- q / 2^l`

sentinel = - q / 2**l

for i, row in enumerate(R):

    if sentinel in row:

        print("\nSentinel found!\n")

        b = Integer(row[i])

        # Calculate the nonce `k`
        k = 2**l * b + S[i]['leak']

        # Validating the nonce
        # by checking if `k * G`'s x-coordinate equals the corresponding `r` value
        if (k * G)[0] != S[i]['r']:
            print("invalid nonce, skipping row...")
            continue

        # Recover the private key `d`
        d = pow(S[i]['r'], -1, q) * (S[i]['s'] * k - S[i]['h']) % q

        print(f"Private key, d: {d}\n")
